# Generated by Django 5.2.8 on 2025-12-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
